CREATE TABLE IF NOT EXISTS USERS( 
	ID int NOT NULL AUTO_INCREMENT, 
	NAME VARCHAR(100) NOT NULL, 
	EMAIL VARCHAR(100) NOT NULL, 
  	PASSWORD varchar(50) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS COMPLAINTS( 
	ID INT NOT NULL AUTO_INCREMENT, 
	USERID INT, 
  	COMPLAINT text NOT NULL,
  	`date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id), 
	FOREIGN KEY(user_id) REFERENCES users(id)
);

